import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
       <Head>
      <title>Portefolio Mohamdou Mansour</title>
      <meta name="description" content="Description de ma page" />
      <link rel="icon" href="favicon.ico" />
    </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
